//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPAPI.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCSEStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCSEStudent()
        {
            this.tblRequirementGrades = new HashSet<tblRequirementGrade>();
        }
    
        public string PK_tblCSEStudents { get; set; }
        public string name { get; set; }
        public Nullable<short> groupId { get; set; }
        public string etag { get; set; }
    
        public virtual tblProjectGroup tblProjectGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRequirementGrade> tblRequirementGrades { get; set; }
    }
}
