//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPAPI.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFyp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFyp()
        {
            this.tblInterestedIns = new HashSet<tblInterestedIn>();
            this.tblProjectGroups = new HashSet<tblProjectGroup>();
            this.tblSupervises = new HashSet<tblSupervis>();
        }
    
        public short PK_tblFyp { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string category { get; set; }
        public string type { get; set; }
        public string otherRequirements { get; set; }
        public short minStudents { get; set; }
        public short maxStudents { get; set; }
        public bool isAvailable { get; set; }
        public string etag { get; set; }
    
        public virtual tblFypCategory tblFypCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInterestedIn> tblInterestedIns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProjectGroup> tblProjectGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSupervis> tblSupervises { get; set; }
    }
}
