//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPAPI.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFaculty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFaculty()
        {
            this.tblProjectGroups = new HashSet<tblProjectGroup>();
            this.tblRequirementGrades = new HashSet<tblRequirementGrade>();
            this.tblSupervises = new HashSet<tblSupervis>();
        }
    
        public string PK_tblFaculties { get; set; }
        public string name { get; set; }
        public string roomNo { get; set; }
        public string facultyCode { get; set; }
        public string etag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProjectGroup> tblProjectGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRequirementGrade> tblRequirementGrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSupervis> tblSupervises { get; set; }
    }
}
