//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPAPI.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProjectGroup()
        {
            this.tblCSEStudents = new HashSet<tblCSEStudent>();
            this.tblInterestedIns = new HashSet<tblInterestedIn>();
        }
    
        public short PK_tblProjectGroups { get; set; }
        public string groupCode { get; set; }
        public Nullable<short> assignedFYP { get; set; }
        public string reader { get; set; }
        public string etag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCSEStudent> tblCSEStudents { get; set; }
        public virtual tblFaculty tblFaculty { get; set; }
        public virtual tblFyp tblFyp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInterestedIn> tblInterestedIns { get; set; }
    }
}
