//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPAPI.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRequirementGrade
    {
        public string facultyUsername { get; set; }
        public string studentUsername { get; set; }
        public Nullable<decimal> proposalReport { get; set; }
        public Nullable<decimal> progressReport { get; set; }
        public Nullable<decimal> finalReport { get; set; }
        public Nullable<decimal> presentation { get; set; }
        public string etag { get; set; }
    
        public virtual tblCSEStudent tblCSEStudent { get; set; }
        public virtual tblFaculty tblFaculty { get; set; }
    }
}
